name: Unzip Files

on:
  push:
    branches:
      - main

jobs:
  unzip:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository content
        uses: actions/checkout@v2

      - name: Install unzip
        run: sudo apt-get install -y unzip

      - name: Unzip files
        run: |
          for file in *.zip.*; do
            cat $file >> combined.zip
          done
          unzip -o combined.zip -d extracted

      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add extracted/*
          git commit -m 'Dezarhivat fișiere zip'
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
